### PR TITLE
Add iteration feature

### PR DESCRIPTION
**Pull request by rivol**
AddedExportedSettings.items() that can be used to iterate over all exported settings.
Iteration abilities are useful if you want to expose all the exported settings in your template.

Also ported the demo app to Django 1.10.

### CODE REVIEW

**Comment by jkbrzt** [comment]
Thanks for the pull request, @rivol!

Good point about the lack of iterability — I've just pushed a bit more robust solution based on subclassing `dict` (see a9ccf05).

Please feel free to open a new pull request with the some of the remaining changes from this PR (just make sure Travis is green).

**Comment by rivol** [comment]
Cool, will do. I also noticed that Travis isn't set up to test with Django >= 1.8 ATM, you might want to change that :-)

**Comment by jkbrzt** [comment]
@rivol great, thanks. 

There's also [Django without version](https://github.com/jkbrzt/django-settings-export/blob/master/.travis.yml#L14) which install the latest version. But sure, we could also include the ones between `1.7` and the currently latest version. Feel free to add that. Cheers

**Comment by rivol** [comment]
I'm trying to port my tests to work with your change, but it's problematic. I still can't use `settings.items` in templates due to the order of variable lookups in templates.

Django first tries dict lookup and relies on specific exceptions being raised if the key is absent from the dict (specifically one of `TypeError, AttributeError, KeyError, ValueError, IndexError`). django-settings-export raises `UnexportedSettingError` which Django treats as fatal error. See https://docs.djangoproject.com/en/1.10/ref/templates/language/#template-variables for more info.

I don't have any good ideas for solving this. Special cases could be added to `__getitem__()` but maybe you've got better ideas?

**Comment by jkbrzt** [comment]
@rivol right, didn't realize this. So let's drop the option to access the values via attributes, It's not actually even needed. These steps should do the trick:

* Remove the `__getattr__()` method definition
* Remove the attribute access mention from the docstring
* Remove `test_attribute_*` tests

Thanks!

**Comment by jkbrzt** [comment]
…that won't actually be enough since it tries key access first, hold on

**Comment by jkbrzt** [comment]
The last missing step (hopefully):

* let the `KeyError` propagate if an attribute of that name exists

```patch
         try:
             return super(ExportedSettings, self).__getitem__(item)
         except KeyError:
+            if hasattr(self, item):
+                raise
             raise UnexportedSettingError(
```

**Comment by rivol** [comment]
Fails on Python 3. AFAICT hasattr() calls getattr() calls __getattr__() = __getitem__() which goes on to call hasattr() again...

**Comment by jkbrzt** [comment]
@rivol true, but `__getattr__` should be removed (see https://github.com/jkbrzt/django-settings-export/pull/4#issuecomment-258618537):

> […]
> * Remove the __getattr__() method definition
> […]

**Comment by rivol** [comment]
@jkbrzt nope, if I remove `__getattr__` then dotted access fails, ala `settings.FOO`

**Comment by jkbrzt** [comment]
Please read the whole comment — I'm suggesting there dropping attribute access altogether :)

**Comment by rivol** [comment]
Oh, right, I missed that part :-P Thanks for sorting this out.
Time for 2.0 now?

**Comment by jkbrzt** [comment]
@rivol done, thanks for you help

https://pypi.python.org/pypi/django-settings-export

**Pull request closed without merging**
